export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GET_ARTICLES_START='GET_ARTICLES_START';
export const GET_ARTICLES_SUCCESS='GET_ARTICLES_SUCCESS';
export const CREATE_NEW_ARTICLE='CREATE_NEW_ARTICLE';
export const DELETE_ARTICLE='DELETE_ARTICLE';
export const START_CREATE_COMMENT='START_CREATE_COMMENT';
export const CREATE_COMMENT='CREATE_COMMENT';
export const DELETE_COMMENT='DELETE_COMMENT';